### ISSUE TITLE
setClassifier and horribleGlobalPath

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/uea-tsc#119]
hi, james has this to be backward compatible with my hack for reading CAWPE from file. I propose we remove classic, my global stings and just have the switch inside setClassifier(ExperimentalArguments a)

any reason not to do this anyone knows of? The only downside is that you need to assume the results files for CAWPEFROMFILE will have to all be in the same directory, and that will have to be where the CAWPEFROMFILE writes to (if you use setClassifier to run this). I have no problem with that.
  
![image](https://user-images.githubusercontent.com/9594042/61941397-4d164500-af8f-11e9-96eb-590f70a18a86.png)

**Comment by TonyBagnall** [comment]
and far be it for me to get all engineering-y, but maybe we should encapsulate these?

**Comment by James-Large** [comment]
We potentially want to keep classic for cases where people aren't running full-blown experiments (and so don't have ExpArgs) but instead just want to instantiate a quick classifier for some local run

Or we keep an overload that takes the classifierName and foldId, and wrap that into an ExpArgs to pass to what will become the 'main' overload

i.e.

move the switch-case into the proper one that takes the ExpArgs object, then just turn the String,int overload into 

```
setClassifier(String cname, int f) {
    ExperimentalArguments exp = ...()
    exp.classifierName = cname 
    exp.foldID = f
    return setClassifier(exp) 
}
```


And on your last comment, yeah there is an argument for splitting the args class into different sub-things, like primary and secondary optionw, as well as an 'ExperimentState' class etc

**Comment by TonyBagnall** [comment]
yes last solution is the best, since I can then factor out the global strings,

**Comment by TonyBagnall** [comment]
done, take a look then this can be closed

**Comment by James-Large** [comment]
On your version, do a quick find usages on the global paths strings to see if they can be completely removed now, they're still being set in setupAndRunExperiment I think, though unsure if any other (e.g. old bakeoff era) classifiers still use it

**Comment by TonyBagnall** [comment]
weird, did a clean and build before pushing. Ah hang on ...

**Comment by TonyBagnall** [comment]
confusing my local version. Will fix, should have PRed this one

**Comment by TonyBagnall** [comment]
so the only time it was ever used was it setClassifier for CAWPEFROMFILE, that was its entire raison d'etre. Think I had caught all uses

**Comment by TonyBagnall** [comment]
could you check from dev though? Is it possible to make it compile whats there in travis? I know, I should work on branch, but this is all cosmetic

**Comment by James-Large** [comment]
based on last commit 17 mins ago, it is successfully building on travis

**Comment by James-Large** [comment]
to dev, that is
