### ISSUE TITLE
vector_classifiers

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/uea-tsc#19]
any thoughts on what to do with this (if anything)
![image](https://user-images.githubusercontent.com/9594042/52332847-af848480-29f3-11e9-98b1-aefef598696a.png)

**Comment by James-Large** [comment]
Need PLSNominalClassifier if you mean that in particular. For that package as a whole, yeah I agree it's a bit weird. It's basically just the dump for anything not TSC specific (which, when it was first made, specifically meant things not in the bakeoff paper iirc). 

At least, we could change to something like this (insert whatever useful name other than 'OtherClassifiers'):

- OtherClassifiers
    - GenericEnsembles
        - Stackers
            - ...
        - WeightedVoters
            - ...
        - EnsembleSelection.java
        - CAWPE
        - ...
    - VectorClassifiers
        - TunedSVM.java 
        - ...

**Comment by TonyBagnall** [comment]
nothing against PLS, it was just highlighted when I took screen shot! Something like that sounds sensible. It is the home for CAWPE and Tuning and we wanted to keep it out of Weka proper code for sensible reasons. We can think on this. I would like a generic classifier tuner with string setting, but it is not high priority.

**Comment by TonyBagnall** [comment]
I've made a couple of changes to this directory, but it could be done better. I'm closing this issue though
