### ISSUE TITLE
TechnicalInformation

### ISSUE THREAD

**Issue by James-Large** [uea-machine-learning/uea-tsc#27]
Another thing we should do from a documentation/public usability povover time is to add to all our own classifiers (where appropriate) the technical information type stuff. 

The interface TechnicalInformationHandler defines getTechnicalInformation() which returns a TechnicalInformation object, essentially defines the bibtex for a paper reference for this classifier, e.g j48:

    /**
       * Returns an instance of a TechnicalInformation object, containing 
       * detailed information about the technical background of this class,
       * e.g., paper reference or book this class is based on.
       * 
       * @return the technical information about this class
       */
    public TechnicalInformation getTechnicalInformation() {
        TechnicalInformation 	result;
    
        result = new TechnicalInformation(Type.BOOK);
        result.setValue(Field.AUTHOR, "Ross Quinlan");
        result.setValue(Field.YEAR, "1993");
        result.setValue(Field.TITLE, "C4.5: Programs for Machine Learning");
        result.setValue(Field.PUBLISHER, "Morgan Kaufmann Publishers");
        result.setValue(Field.ADDRESS, "San Mateo, CA");
    
        return result;
    }

**Comment by TonyBagnall** [comment]
I've done that for most of them
![image](https://user-images.githubusercontent.com/9594042/52798101-2ca49f00-306f-11e9-9ce5-4ceb1e6b87c2.png)

**Comment by James-Large** [comment]
Ah yeah, can see that the bakeoff classifiers I've quickly looked at implement the method, but not the interface, i.e. theyre not overriding the abstract method, just declaring it anew

Not massively important by any stretch but can go round at some point and tidy these all up, will add it to cawpe etc

**Comment by TonyBagnall** [comment]
there is also the header. Weka has this at the start

**Comment by TonyBagnall** [comment]
Added the implements to those that have it, still need to check those that do not have it.

**Comment by TonyBagnall** [comment]
Mostly done
