### ISSUE TITLE
Implementation of TunedClassifier

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/uea-tsc#28]
one issue is how to deal with parameters that are dependent on the data. So for example number of features in TSF is sqrt(m).

**Comment by James-Large** [comment]
For simple data dependent things like a proportion of numatts/numinsts/numclasses etc, where e.g maybe the intended space is 

`m/10, 2m/10, 3m/10... log(m), sqrt(m)`

You'd probably have to do something like this 

    //default to 1/10 when using untuned, say
    Function<int, int> numFeatsFinder = (int numAtts) -> { return numAtts * 0.1 } 

     void setOptions(String[])  {
        //other options...
        ....
        propString = //find val for the prop flag
        try 
             prop = parseDouble(propString)
             numFeatsFinder = (int numAtts) -> { return numAtts * prop } 
        catch 
             if propString.equal(sqrt)
                  numFeatsFinder = (int numAtts) -> { return Math.sqrt(numAtts) } 
             else if 
                  //etc
    }

    ....

    buildClassifier(insts)
        numFeats = numFeatsFinder.apply(numAtts)
        ...
   

Same thing could maybe work for more complex data-dependent things too? Cant think of an obvious thing that this wouldn't work for.

**Comment by TonyBagnall** [comment]
so numFeatsFinder is an attribute of the classifier called in buildClassifier? Yeah, like that. If we want sqrt or log we can just switch on the options string. This is a nice application for lambdas.

**Comment by James-Large** [comment]
> so numFeatsFinder is an attribute of the classifier called in buildClassifier?

Yeah

**Comment by TonyBagnall** [comment]
so Function<int,int> is not valid in Java, needs references. I can wrap it in Integer, but it is hideous
    Function<Integer,Integer> numFeatsFinder = (Integer numAtts) -> (Integer)(int)(Math.sqrt(numAtts));   
cast to int then Integer, lol. I like this more
    private interface FeatureFinder{
        int findNumFeatures(int n);
    }
    FeatureFinder numFeatsFinder = (int numAtts) -> (int)(Math.sqrt(numAtts));   
but we could put FeatureFinder somewhere others could access it?

**Comment by James-Large** [comment]
can do all the casts implicitly like this 

    static Function<Integer,Integer> numFeatsFinder = (numAtts) -> (int)(Math.sqrt(numAtts));
    
    public static void main(String[] args) throws Exception {
        int numFeats = numFeatsFinder.apply(10);

spawning interfaces like that would potentially mean we need A LOT of them. You could rename that one to something more generic than feature finder (intToIntFunc or something) to cover cases like numFolds being set in relation to numInstances, but would still need interfaces for int to double, double to double, long to long, etc whenever they end up being needed

**Comment by TonyBagnall** [comment]
yeah I meant for it to be moved up, but no real need for the interface except for clarity. I initially thought it would box it. However 
![image](https://user-images.githubusercontent.com/9594042/52862342-fb8aa400-312c-11e9-8e27-fbccb4ce157d.png)
but it was just the argument cast causing the problem, I thought it would be the same for both. This works
![image](https://user-images.githubusercontent.com/9594042/52862394-19f09f80-312d-11e9-8bd4-752a5bcda06c.png)

**Comment by James-Large** [comment]
These "shouldn't" be needed anywhere other than within the particular classifier, i.e. should probably be private, so having the bespoke Function<Integer,Integer> reference type as opposed to a conceptually higher level interface reference should be fine 

If the lambdas were being passed around between classifiers etc, then yeah we'd need interfaces

**Comment by TonyBagnall** [comment]
its fine now the casting is ok. I'm going to push TSF soon, can you take a look? We then need to decide on a mechanism for getting ranges

**Comment by TonyBagnall** [comment]
the Java Utils for parsing arguments does not work as expected. I'm sure I can work it out, but given how hokey it is, shall we just write our own that puts them in a hash map?
![image](https://user-images.githubusercontent.com/9594042/52865286-38a66480-3134-11e9-9d4f-5d1e7d8c03ed.png)

**Comment by TonyBagnall** [comment]
some right crap in this Utils 
![image](https://user-images.githubusercontent.com/9594042/52865378-6be8f380-3134-11e9-84f8-062d1ab15528.png)

**Comment by James-Large** [comment]
we'd still need to go through setOptions(String[]) ofc, but yeah, in our own classifiers' setOptions(String[]) we can just do

    void setOptions(String[] ops) {
         ParameterSet pset = ParameterSet.fromOptionsArray(ops)
     
         if (pset.get("numFeats"))
              ...
         ....


i have the placeholder in the parameterset class already actually 

    public String[] toOptionsList() { 
        String[] ps = new String[parameterSet.size() * 2];

        int i = 0;
        for (Map.Entry<String, String> entry : parameterSet.entrySet()) {
            ps[i] = "-" + entry.getKey();
            ps[i+1] = entry.getValue();
            i+=2;
        }

        return ps;
    }
    
    /**
     * Assumes that this is just a list of flag-value pairs, e.g 
     * [ flag1, value1, flag2, value2....] 
     * and does not contain any independent flags (maybe representing that a boolean 
     * flag should be set to true, for example), and that all the flag/value pairs 
     * are parameter to be read in (e.g no debug flags)
     */
    public void readOptionsList(String[] options) { 
        //todo
    }

**Comment by James-Large** [comment]
though you dont have access to that yet, im just quickly finishing off a basic contracting implementation of tunedclassifier (which includes the stat of a parameterset implementation), then that'll be all of the interfaces done for that.  Let me get that done quickly and i'll push/pull request

**Comment by TonyBagnall** [comment]
ok, well maybe, I've done it with Utils for now, just tarting up TSF with comments and all! Get me!

**Comment by TonyBagnall** [comment]
closing this as version 1 is there
