### ISSUE TITLE
[BUG] Last value in PLAID dataset all seem to be zero

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/uea-tsc#79]
double check this and if true, remove the redundant feature

**Comment by patrickzib** [comment]
for completeness - these are the labels:

PLAID

0	AirConditioner
1	CompactFluorescentLamp
2	Fan
3	Fridge
4	Hairdryer
5	Heater
6	IncandescentLightBulb
7	Laptop
8	Microwave
9	Vacuum
10	WashingMachine

total number of instances: 1074
number of unique appliance types: 11

           Appliance Type	# instances
          Air Conditioner	        66
 Compact Fluorescent Lamp	       175
                      Fan	       115
                   Fridge	        38
                Hairdryer	       156
                   Heater	        35
  Incandescent Light Bulb	       114
                   Laptop	       172
                Microwave	       139
                   Vacuum	        38
          Washing Machine	        26

**Comment by TonyBagnall** [comment]
moved to new repo
