### ISSUE TITLE
ShapeletTransform duplicates

### ISSUE THREAD

**Issue by TonyBagnall** [uea-machine-learning/uea-tsc#89]
I'd like a check to not allow exactly the same shapelets. Generally wont be an issue. This arose because flat lines are discriminatory in Yoga. So shapelet 0,0,0 appears multiple times, thus wasting shapelet allocation

**Comment by ABostrom** [comment]
I'll make this a flag.

When adding to the current best set, if the IG is the same, and theyre the same length, then check the distance between the shapelet that you're proposing to add, and the current one in the set, if the distance is 0. Don't bother adding it?

**Comment by TonyBagnall** [comment]
sounds sensible, should not slow stuff down. In fact it gives us a mechanism to test alternative entry conditions, as its an obvious thing to try to  maintain diversity. in the future!

**Comment by ABostrom** [comment]
#104
